# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 04:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_client_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('backer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_backer', to=settings.AUTH_USER_MODEL)),
                ('entreprenuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_entreprenuer', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Project')),
            ],
        ),
    ]
